using System.ComponentModel;
using System.Globalization;
using System.Runtime.CompilerServices;

namespace VinhKhanh.Services
{
    public class LocalizationService : INotifyPropertyChanged
    {
        private static LocalizationService? _instance;
        private string _currentLanguage = "vi";

        public event EventHandler? LanguageChanged;
        public event PropertyChangedEventHandler? PropertyChanged;

        private static readonly Dictionary<string, Dictionary<string, string>> Translations = new()
        {
            {
                "vi", new Dictionary<string, string>
                {
                    { "Settings", "Cài Đặt" },
                    { "Language", "🌐 Ngôn Ngữ" },
                    { "Vietnamese", "🇻🇳 Tiếng Việt" },
                    { "English", "🇬🇧 English" },
                    { "Notifications", "🔔 Thông Báo" },
                    { "NotificationDesc", "Nhận thông báo khi gần quán ăn" },
                    { "About", "ℹ️ Thông Tin" },
                    { "AppName", "Phố Ẩm Thực Vĩnh Khánh" },
                    { "Version", "Phiên bản: 1.0.0" },
                    { "Explore", "Khám Phá" },
                    { "StreetFood", "Phố Ẩm Thực" },
                    { "Vinh", "Vĩnh" },
                    { "Khanh", "Khánh" },
                    { "SearchPlaceholder", "Tìm kiếm quán ăn..." },
                    { "Results", "kết quả" },
                    { "ViewDetails", "📋 Chi tiết" },
                    { "Play", "🔊 Nghe" },
                    { "MapNotLoaded", "Không tải được Map SDK." },
                    { "MapArea", "Bản đồ khu vực" },
                    { "Categories", "Danh mục" },
                    { "RestaurantsNearYou", "Quán ăn gần bạn" },
                    { "CurrentLocation", "Vị trí hiện tại:" },
                    { "District1HCMC", "Quận 1, TP. HCM" },
                    { "YearEstablished", "Thành lập" },
                    { "SignatureDish", "Món Đặc Biệt" },
                    { "Menu", "Thực Đơn" },
                    { "Audio", "Âm Thanh" },
                    { "Address", "Địa chỉ" },
                    { "NarrationLanguage", "Ngôn ngữ thuyết minh" },
                    { "Vi", "Tiếng Việt" },
                    { "En", "English" },
                    { "SaveRestaurant", "💾 Lưu Quán" },
                    { "SavedRestaurant", "✓ Đã Lưu" },
                    { "RemoveFromSaved", "❌ Bỏ Lưu" },
                    { "SaveSuccess", "Lưu thành công" },
                    { "RemoveSuccess", "Bỏ lưu thành công" },
                    { "SaveError", "Lỗi khi lưu" },
                    { "RemoveError", "Lỗi khi bỏ lưu" },
                    { "Success", "Thành công" },
                    { "Saved", "Đã Lưu" },
                    { "Tracking", "Theo Dõi" },
                    { "QRCode", "Quét QR" },
                    { "DataError", "Lỗi dữ liệu" },
                    { "CannotLoadData", "Không thể đọc dữ liệu" },
                    { "Error", "Lỗi" },
                    { "CannotLoadPage", "Không thể tải trang" },
                    { "OK", "Được" },
                    { "Tracking_Status_Completed", "Phát thuyết minh xong" },
                    { "Tracking_Status_Playing", "Đang phát thuyết minh" },
                    { "Tracking_Status_Approaching", "Sắp đến" },
                    { "NoSavedRestaurants", "Chưa có quán ăn nào được lưu" },
                    { "SavedRestaurantsLabel", "📍 Đã lưu" },
                    { "ListenButton", "🔊 Nghe" },
                    { "DetailsButton", "📋 Chi tiết" },
                    { "ScanQR", "Quét Mã QR" },
                    { "QRInstruction", "📱 Hướng camera vào mã QR" },
                    { "QRDetected", "Quét Mã QR Thành Công" },
                    { "QRResult", "Kết quả" },
                    { "CameraPermissionError", "Ứng dụng cần quyền truy cập camera để quét mã QR" },
                    { "PermissionError", "Lỗi yêu cầu quyền" },
                    { "PermissionUnknownError", "Không thể xác định trạng thái quyền camera. Vui lòng kiểm tra cài đặt ứng dụng." },
                    { "FlashlightNotSupported", "Thiết bị không hỗ trợ đèn pin" },
                    { "RestaurantNotFound", "❌ Không tìm thấy nhà hàng" },
                    { "ScanOtherQR", "Vui lòng quét mã QR khác" },
                    { "LoadRestaurantError", "❌ Lỗi khi tải dữ liệu nhà hàng:" },
                    { "StartTracking", "▶️ Bật Theo Dõi" },
                    { "StopTracking", "⏸️ Tắt Theo Dõi" },
                    { "CurrentLocationTracking", "📍 Vị Trí Hiện Tại" },
                    { "WaitingGPS", "Chờ GPS..." },
                    { "Status", "🔊 Trạng Thái" },
                    { "Ready", "Sẵn sàng" },
                    { "Tracking_Enabled", "Đang theo dõi vị trí..." },
                    { "TrackingSuccess", "Thành công" },
                    { "TrackingStarted", "Đã bật theo dõi vị trí" },
                    { "TrackingStopped", "Đã tắt theo dõi vị trí" },
                    { "TrackingError", "Không thể" },
                    { "StartTrackingError", "Không thể bật theo dõi" },
                    { "StopTrackingError", "Không thể tắt theo dõi" },
                    { "LocationError", "Lỗi cập nhật vị trí" },
                    { "StatusError", "Lỗi cập nhật trạng thái" },
                    { "NearbyRestaurants", "🍽️ Quán Ăn Gần Bạn" },
                    { "Latitude", "Vĩ độ" },
                    { "Longitude", "Kinh độ" },
                    { "LocationPermissionDenied", "Quyền vị trí bị từ chối" },
                    { "LocationTrackingError", "Lỗi theo dõi vị trí" },
                    { "RestaurantDetailTitle", "Chi Tiết Quán Ăn" },
                    { "History", "Lịch Sử" },
                    { "Introduction", "Giới thiệu" },
                    { "FeaturedMenu", "Menu Nổi Bật" },
                    { "NoMenuData", "Chưa có dữ liệu menu" },
                    { "PlaybackControls", "Điều Khiển Phát" },
                    { "ListenStoryButton", "🔊 Nghe Câu Chuyện" },
                    { "Zh", "中文" },
                    { "Ja", "日本語" },
                    { "Ru", "Русский" },
                    { "Fr", "Français" },
                }
            },
            {
                "en", new Dictionary<string, string>
                {
                    { "Settings", "Settings" },
                    { "Language", "🌐 Language" },
                    { "Vietnamese", "🇻🇳 Vietnamese" },
                    { "English", "🇬🇧 English" },
                    { "Notifications", "🔔 Notifications" },
                    { "NotificationDesc", "Receive notifications when near a restaurant" },
                    { "About", "ℹ️ About" },
                    { "AppName", "Vinh Khanh Street Food" },
                    { "Version", "Version: 1.0.0" },
                    { "Explore", "Explore" },
                    { "StreetFood", "Street Food" },
                    { "Vinh", "Vinh" },
                    { "Khanh", "Khanh" },
                    { "SearchPlaceholder", "Search restaurants..." },
                    { "Results", "results" },
                    { "ViewDetails", "📋 Details" },
                    { "Play", "🔊 Listen" },
                    { "MapNotLoaded", "Could not load Map SDK." },
                    { "MapArea", "Area Map" },
                    { "Categories", "Categories" },
                    { "RestaurantsNearYou", "Restaurants near you" },
                    { "CurrentLocation", "Current location:" },
                    { "District1HCMC", "District 1, Ho Chi Minh City" },
                    { "YearEstablished", "Established" },
                    { "SignatureDish", "Signature Dish" },
                    { "Menu", "Menu" },
                    { "Audio", "Audio" },
                    { "Address", "Address" },
                    { "NarrationLanguage", "Narration language" },
                    { "Vi", "Vietnamese" },
                    { "En", "English" },
                    { "SaveRestaurant", "💾 Save Restaurant" },
                    { "SavedRestaurant", "✓ Saved" },
                    { "RemoveFromSaved", "❌ Remove" },
                    { "SaveSuccess", "Saved successfully" },
                    { "RemoveSuccess", "Removed successfully" },
                    { "SaveError", "Error saving" },
                    { "RemoveError", "Error removing" },
                    { "Success", "Success" },
                    { "Saved", "Saved" },
                    { "Tracking", "Tracking" },
                    { "QRCode", "Scan QR" },
                    { "DataError", "Data Error" },
                    { "CannotLoadData", "Cannot read data" },
                    { "Error", "Error" },
                    { "CannotLoadPage", "Cannot load page" },
                    { "OK", "OK" },
                    { "Tracking_Status_Completed", "Playback completed" },
                    { "Tracking_Status_Playing", "Now playing narration" },
                    { "Tracking_Status_Approaching", "Approaching" },
                    { "NoSavedRestaurants", "No saved restaurants yet" },
                    { "SavedRestaurantsLabel", "📍 Saved" },
                    { "ListenButton", "🔊 Listen" },
                    { "DetailsButton", "📋 Details" },
                    { "ScanQR", "Scan QR Code" },
                    { "QRInstruction", "📱 Point camera at QR code" },
                    { "QRDetected", "QR Code Scanned Successfully" },
                    { "QRResult", "Result" },
                    { "CameraPermissionError", "The application needs camera access permission to scan QR codes" },
                    { "PermissionError", "Permission Error" },
                    { "PermissionUnknownError", "Cannot determine camera permission status. Please check application settings." },
                    { "FlashlightNotSupported", "Device does not support flashlight" },
                    { "RestaurantNotFound", "❌ Restaurant not found" },
                    { "ScanOtherQR", "Please scan another QR code" },
                    { "LoadRestaurantError", "❌ Error loading restaurant data:" },
                    { "StartTracking", "▶️ Start Tracking" },
                    { "StopTracking", "⏸️ Stop Tracking" },
                    { "CurrentLocationTracking", "📍 Current Location" },
                    { "WaitingGPS", "Waiting for GPS..." },
                    { "Status", "🔊 Status" },
                    { "Ready", "Ready" },
                    { "Tracking_Enabled", "Tracking location..." },
                    { "TrackingSuccess", "Success" },
                    { "TrackingStarted", "Location tracking enabled" },
                    { "TrackingStopped", "Location tracking disabled" },
                    { "TrackingError", "Error" },
                    { "StartTrackingError", "Cannot enable tracking" },
                    { "StopTrackingError", "Cannot disable tracking" },
                    { "LocationError", "Location update error" },
                    { "StatusError", "Status update error" },
                    { "NearbyRestaurants", "🍽️ Nearby Restaurants" },
                    { "Latitude", "Latitude" },
                    { "Longitude", "Longitude" },
                    { "LocationPermissionDenied", "Location permission was denied" },
                    { "LocationTrackingError", "Location tracking error" },
                    { "RestaurantDetailTitle", "Restaurant Details" },
                    { "History", "History" },
                    { "Introduction", "Introduction" },
                    { "FeaturedMenu", "Featured Menu" },
                    { "NoMenuData", "No menu data available" },
                    { "PlaybackControls", "Playback Controls" },
                    { "ListenStoryButton", "🔊 Listen to Story" },
                    { "Zh", "Chinese" },
                    { "Ja", "Japanese" },
                    { "Ru", "Russian" },
                    { "Fr", "French" },
                }
            },
            {
                "zh", new Dictionary<string, string>
                {
                    { "Settings", "设置" },
                    { "Language", "🌐 语言" },
                    { "StreetFood", "街头美食" },
                    { "MapArea", "区域地图" },
                    { "Categories", "类别" },
                    { "RestaurantsNearYou", "附近餐厅" },
                    { "CurrentLocation", "当前位置:" },
                    { "YearEstablished", "成立年份" },
                    { "SignatureDish", "招牌菜" },
                    { "Menu", "菜单" },
                    { "Audio", "音频" },
                    { "Address", "地址" },
                    { "NarrationLanguage", "解说语言" },
                    { "Vi", "越南语" },
                    { "En", "英语" },
                    { "SaveRestaurant", "💾 保存餐厅" },
                    { "SavedRestaurant", "✓ 已保存" },
                    { "RemoveFromSaved", "❌ 移除" },
                    { "SaveSuccess", "保存成功" },
                    { "RemoveSuccess", "移除成功" },
                    { "SaveError", "保存错误" },
                    { "RemoveError", "移除错误" },
                    { "Success", "成功" },
                    { "Saved", "已保存" },
                    { "Tracking", "追踪" },
                    { "QRCode", "扫码" },
                    { "DataError", "数据错误" },
                    { "CannotLoadData", "无法读取数据" },
                    { "Error", "错误" },
                    { "CannotLoadPage", "无法加载页面" },
                    { "OK", "确定" },
                    { "Tracking_Status_Completed", "播放完成" },
                    { "Tracking_Status_Playing", "正在播放解说" },
                    { "Tracking_Status_Approaching", "靠近中" },
                    { "NoSavedRestaurants", "暂无保存的餐厅" },
                    { "SavedRestaurantsLabel", "📍 已保存的餐厅" },
                    { "ListenButton", "🔊 收听" },
                    { "DetailsButton", "📋 详情" },
                    { "ScanQR", "扫描二维码" },
                    { "QRInstruction", "📱 对准二维码" },
                    { "QRDetected", "二维码扫描成功" },
                    { "QRResult", "结果" },
                    { "CameraPermissionError", "应用需要相机访问权限来扫描二维码" },
                    { "PermissionError", "权限错误" },
                    { "PermissionUnknownError", "无法确定相机权限状态。请检查应用设置。" },
                    { "FlashlightNotSupported", "设备不支持闪光灯" },
                    { "RestaurantNotFound", "❌ 找不到餐厅" },
                    { "ScanOtherQR", "请扫描其他二维码" },
                    { "LoadRestaurantError", "❌ 加载餐厅数据错误:" },
                    { "StartTracking", "▶️ 开始追踪" },
                    { "StopTracking", "⏸️ 停止追踪" },
                    { "CurrentLocationTracking", "📍 当前位置信息" },
                    { "WaitingGPS", "等待GPS..." },
                    { "Status", "🔊 状态" },
                    { "Ready", "准备好" },
                    { "Tracking_Enabled", "正在追踪位置信息..." },
                    { "TrackingSuccess", "成功" },
                    { "TrackingStarted", "已启用位置追踪" },
                    { "TrackingStopped", "已禁用位置追踪" },
                    { "TrackingError", "错误" },
                    { "StartTrackingError", "无法启用追踪" },
                    { "StopTrackingError", "无法禁用追踪" },
                    { "LocationError", "位置更新错误" },
                    { "StatusError", "状态更新错误" },
                    { "NearbyRestaurants", "🍽️ 附近餐厅" },
                    { "Latitude", "纬度" },
                    { "Longitude", "经度" },
                    { "LocationPermissionDenied", "位置权限已被拒绝" },
                    { "LocationTrackingError", "位置追踪错误" },
                    { "RestaurantDetailTitle", "餐厅详情" },
                    { "History", "历史记录" },
                    { "Introduction", "介绍" },
                    { "FeaturedMenu", "特色菜单" },
                    { "NoMenuData", "暂无菜单数据" },
                    { "PlaybackControls", "播放控制" },
                    { "ListenStoryButton", "🔊 收听故事" },
                    { "Fr", "法语" },
                }
            },
            {
                "ja", new Dictionary<string, string>
                {
                    { "Settings", "設定" },
                    { "Language", "🌐 言語" },
                    { "StreetFood", "ストリートフード" },
                    { "MapArea", "エリアマップ" },
                    { "Categories", "カテゴリー" },
                    { "RestaurantsNearYou", "近くのレストラン" },
                    { "CurrentLocation", "現在地:" },
                    { "YearEstablished", "設立年" },
                    { "SignatureDish", "名物料理" },
                    { "Menu", "メニュー" },
                    { "Audio", "オーディオ" },
                    { "Address", "住所" },
                    { "NarrationLanguage", "ナレーション言語" },
                    { "Vi", "ベトナム語" },
                    { "En", "英語" },
                    { "SaveRestaurant", "💾 レストランを保存" },
                    { "SavedRestaurant", "✓ 保存済み" },
                    { "RemoveFromSaved", "❌ 削除" },
                    { "SaveSuccess", "保存に成功しました" },
                    { "RemoveSuccess", "削除に成功しました" },
                    { "SaveError", "保存エラー" },
                    { "RemoveError", "削除エラー" },
                    { "Success", "成功" },
                    { "Saved", "保存済み" },
                    { "Tracking", "追跡" },
                    { "QRCode", "QRコードスキャン" },
                    { "DataError", "データエラー" },
                    { "CannotLoadData", "データを読み込めません" },
                    { "Error", "エラー" },
                    { "CannotLoadPage", "ページを読み込めません" },
                    { "OK", "OK" },
                    { "Tracking_Status_Completed", "再生完了" },
                    { "Tracking_Status_Playing", "ナレーション再生中" },
                    { "Tracking_Status_Approaching", "接近中" },
                    { "NoSavedRestaurants", "保存済みのレストランはありません" },
                    { "SavedRestaurantsLabel", "📍 保存済み" },
                    { "ListenButton", "🔊 聞く" },
                    { "DetailsButton", "📋 詳細" },
                    { "ScanQR", "QRコードをスキャン" },
                    { "QRInstruction", "📱 QRコードにカメラを合わせてください" },
                    { "QRDetected", "QRコードのスキャンに成功" },
                    { "QRResult", "結果" },
                    { "CameraPermissionError", "アプリはQRコードをスキャンするためにカメラアクセス権が必要です" },
                    { "PermissionError", "権限エラー" },
                    { "PermissionUnknownError", "カメラの権限ステータスを確認できません。アプリ設定を確認してください。" },
                    { "FlashlightNotSupported", "デバイスはフラッシュライトをサポートしていません" },
                    { "RestaurantNotFound", "❌ レストランが見つかりません" },
                    { "ScanOtherQR", "別のQRコードをスキャンしてください" },
                    { "LoadRestaurantError", "❌ レストランデータの読み込みエラー:" },
                    { "StartTracking", "▶️ 追跡を開始" },
                    { "StopTracking", "⏸️ 追跡を停止" },
                    { "CurrentLocationTracking", "📍 現在地" },
                    { "WaitingGPS", "GPSを待っています..." },
                    { "Status", "🔊 ステータス" },
                    { "Ready", "準備完了" },
                    { "Tracking_Enabled", "位置情報を追跡中..." },
                    { "TrackingSuccess", "成功" },
                    { "TrackingStarted", "位置追跡が有効になりました" },
                    { "TrackingStopped", "位置追跡が無効になりました" },
                    { "TrackingError", "エラー" },
                    { "StartTrackingError", "追跡を有効にできません" },
                    { "StopTrackingError", "追跡を無効にできません" },
                    { "LocationError", "位置更新エラー" },
                    { "StatusError", "ステータス更新エラー" },
                    { "NearbyRestaurants", "🍽️ 近くのレストラン" },
                    { "Latitude", "緯度" },
                    { "Longitude", "経度" },
                    { "LocationPermissionDenied", "位置情報の権限が拒否されました" },
                    { "LocationTrackingError", "位置追跡エラー" },
                    { "RestaurantDetailTitle", "レストラン詳細" },
                    { "History", "履歴" },
                    { "Introduction", "紹介" },
                    { "FeaturedMenu", "おすすめメニュー" },
                    { "NoMenuData", "メニューデータがありません" },
                    { "PlaybackControls", "再生コントロール" },
                    { "ListenStoryButton", "🔊 ストーリーを聞く" },
                }
            },
            {
                "ru", new Dictionary<string, string>
                {
                    { "Settings", "Настройки" },
                    { "Language", "🌐 Язык" },
                    { "StreetFood", "Уличная еда" },
                    { "MapArea", "Карта района" },
                    { "Categories", "Категории" },
                    { "RestaurantsNearYou", "Рестораны рядом" },
                    { "CurrentLocation", "Текущее местоположение:" },
                    { "YearEstablished", "Год основания" },
                    { "SignatureDish", "Фирменное блюдо" },
                    { "Menu", "Меню" },
                    { "Audio", "Аудио" },
                    { "Address", "Адрес" },
                    { "NarrationLanguage", "Язык озвучки" },
                    { "Vi", "Вьетнамский" },
                    { "En", "Английский" },
                    { "SaveRestaurant", "💾 Сохранить ресторан" },
                    { "SavedRestaurant", "✓ Сохранено" },
                    { "RemoveFromSaved", "❌ Удалить" },
                    { "SaveSuccess", "Сохранено успешно" },
                    { "RemoveSuccess", "Удалено успешно" },
                    { "SaveError", "Ошибка сохранения" },
                    { "RemoveError", "Ошибка удаления" },
                    { "Success", "Успех" },
                    { "Saved", "Сохранено" },
                    { "Tracking", "Отслеживание" },
                    { "QRCode", "QR-сканер" },
                    { "DataError", "Ошибка данных" },
                    { "CannotLoadData", "Не удается прочитать данные" },
                    { "Error", "Ошибка" },
                    { "CannotLoadPage", "Не удается загрузить страницу" },
                    { "OK", "OK" },
                    { "Tracking_Status_Completed", "Проигрывание завершено" },
                    { "Tracking_Status_Playing", "Сейчас воспроизводится" },
                    { "Tracking_Status_Approaching", "Приближается" },
                    { "NoSavedRestaurants", "Нет сохраненных ресторанов" },
                    { "SavedRestaurantsLabel", "📍 Сохраненные" },
                    { "ListenButton", "🔊 Слушать" },
                    { "DetailsButton", "📋 Подробнее" },
                    { "ScanQR", "Сканировать QR-код" },
                    { "QRInstruction", "📱 Наведите камеру на QR-код" },
                    { "QRDetected", "QR-код успешно отсканирован" },
                    { "QRResult", "Результат" },
                    { "CameraPermissionError", "Приложение требует разрешения на доступ к камере для сканирования QR-кодов" },
                    { "PermissionError", "Ошибка прав" },
                    { "PermissionUnknownError", "Не удается определить статус прав камеры. Пожалуйста, проверьте настройки приложения." },
                    { "FlashlightNotSupported", "Устройство не поддерживает вспышку" },
                    { "RestaurantNotFound", "❌ Ресторан не найден" },
                    { "ScanOtherQR", "Пожалуйста, отсканируйте другой QR-код" },
                    { "LoadRestaurantError", "❌ Ошибка загрузки данных ресторана:" },
                    { "StartTracking", "▶️ Начать отслеживание" },
                    { "StopTracking", "⏸️ Остановить отслеживание" },
                    { "CurrentLocationTracking", "📍 Текущее местоположение" },
                    { "WaitingGPS", "Ожидание GPS..." },
                    { "Status", "🔊 Статус" },
                    { "Ready", "Готово" },
                    { "Tracking_Enabled", "Отслеживание местоположения..." },
                    { "TrackingSuccess", "Успех" },
                    { "TrackingStarted", "Отслеживание местоположения включено" },
                    { "TrackingStopped", "Отслеживание местоположения выключено" },
                    { "TrackingError", "Ошибка" },
                    { "StartTrackingError", "Не удается включить отслеживание" },
                    { "StopTrackingError", "Не удается выключить отслеживание" },
                    { "LocationError", "Ошибка обновления местоположения" },
                    { "StatusError", "Ошибка обновления статуса" },
                    { "NearbyRestaurants", "🍽️ Рестораны поблизости" },
                    { "Latitude", "Широта" },
                    { "Longitude", "Долгота" },
                    { "LocationPermissionDenied", "Разрешение на доступ к местоположению отклонено" },
                    { "LocationTrackingError", "Ошибка отслеживания местоположения" },
                    { "RestaurantDetailTitle", "Детали ресторана" },
                    { "History", "История" },
                    { "Introduction", "Введение" },
                    { "FeaturedMenu", "Рекомендуемое меню" },
                    { "NoMenuData", "Нет данных меню" },
                    { "PlaybackControls", "Управление воспроизведением" },
                    { "ListenStoryButton", "🔊 Слушать историю" },
                }
            },
            {
                "fr", new Dictionary<string, string>
                {
                    { "Settings", "Paramètres" },
                    { "Language", "🌐 Langue" },
                    { "StreetFood", "Street Food" },
                    { "MapArea", "Carte de la zone" },
                    { "Categories", "Catégories" },
                    { "RestaurantsNearYou", "Restaurants près de vous" },
                    { "CurrentLocation", "Position actuelle :" },
                    { "YearEstablished", "Fondé en" },
                    { "SignatureDish", "Plat signature" },
                    { "Menu", "Menu" },
                    { "Audio", "Audio" },
                    { "Address", "Adresse" },
                    { "NarrationLanguage", "Langue de narration" },
                    { "Vi", "Vietnamien" },
                    { "En", "Anglais" },
                    { "SaveRestaurant", "💾 Enregistrer le restaurant" },
                    { "SavedRestaurant", "✓ Enregistré" },
                    { "RemoveFromSaved", "❌ Retirer" },
                    { "SaveSuccess", "Enregistré avec succès" },
                    { "RemoveSuccess", "Retiré avec succès" },
                    { "SaveError", "Erreur d'enregistrement" },
                    { "RemoveError", "Erreur de retrait" },
                    { "Success", "Succès" },
                    { "Saved", "Enregistré" },
                    { "Tracking", "Suivi" },
                    { "QRCode", "Scanner QR" },
                    { "DataError", "Erreur de données" },
                    { "CannotLoadData", "Impossible de lire les données" },
                    { "Error", "Erreur" },
                    { "CannotLoadPage", "Impossible de charger la page" },
                    { "OK", "OK" },
                    { "Tracking_Status_Completed", "Lecture terminée" },
                    { "Tracking_Status_Playing", "Lecture de la narration en cours" },
                    { "Tracking_Status_Approaching", "Approche" },
                    { "NoSavedRestaurants", "Aucun restaurant enregistré" },
                    { "SavedRestaurantsLabel", "📍 Enregistré" },
                    { "ListenButton", "🔊 Écouter" },
                    { "DetailsButton", "📋 Détails" },
                    { "ScanQR", "Scanner le code QR" },
                    { "QRInstruction", "📱 Dirigez la caméra vers le code QR" },
                    { "QRDetected", "Code QR scanné avec succès" },
                    { "QRResult", "Résultat" },
                    { "CameraPermissionError", "L'application nécessite l'autorisation d'accès à la caméra pour scanner les codes QR" },
                    { "PermissionError", "Erreur de permission" },
                    { "PermissionUnknownError", "Impossible de déterminer l'état de la permission de la caméra. Veuillez vérifier les paramètres de l'application." },
                    { "FlashlightNotSupported", "L'appareil ne prend pas en charge la lampe de poche" },
                    { "RestaurantNotFound", "❌ Restaurant non trouvé" },
                    { "ScanOtherQR", "Veuillez scanner un autre code QR" },
                    { "LoadRestaurantError", "❌ Erreur de chargement des données du restaurant:" },
                    { "StartTracking", "▶️ Démarrer le suivi" },
                    { "StopTracking", "⏸️ Arrêter le suivi" },
                    { "CurrentLocationTracking", "📍 Informations sur la position actuelle" },
                    { "WaitingGPS", "En attente du GPS..." },
                    { "Status", "🔊 Statut" },
                    { "Ready", "Prêt" },
                    { "Tracking_Enabled", "Suivi de la position en cours..." },
                    { "TrackingSuccess", "Succès" },
                    { "TrackingStarted", "Suivi de la position activé" },
                    { "TrackingStopped", "Suivi de la position désactivé" },
                    { "TrackingError", "Erreur" },
                    { "StartTrackingError", "Impossible d'activer le suivi" },
                    { "StopTrackingError", "Impossible de désactiver le suivi" },
                    { "LocationError", "Erreur de mise à jour de la position" },
                    { "StatusError", "Erreur de mise à jour du statut" },
                    { "NearbyRestaurants", "🍽️ Restaurants à proximité" },
                    { "Latitude", "Latitude" },
                    { "Longitude", "Longitude" },
                    { "LocationPermissionDenied", "La permission d'accès à la position a été refusée" },
                    { "LocationTrackingError", "Erreur de suivi de la position" },
                    { "RestaurantDetailTitle", "Détails du restaurant" },
                    { "History", "Historique" },
                    { "Introduction", "Introduction" },
                    { "FeaturedMenu", "Menu vedette" },
                    { "NoMenuData", "Aucune donnée de menu" },
                    { "PlaybackControls", "Contrôles de lecture" },
                    { "ListenStoryButton", "🔊 Écouter l'histoire" },
                }
            }
        };

        public static LocalizationService Instance => _instance ??= new LocalizationService();

        public string CurrentLanguage
        {
            get => _currentLanguage;
            set
            {
                var normalized = NormalizeLanguageCode(value);
                if (_currentLanguage != normalized)
                {
                    _currentLanguage = normalized;
                    CultureInfo.CurrentUICulture = new CultureInfo(normalized);
                    OnPropertyChanged();
                    LanguageChanged?.Invoke(this, EventArgs.Empty);
                }
            }
        }

        private void OnPropertyChanged([CallerMemberName] string? propertyName = null)
            => PropertyChanged?.Invoke(this, new PropertyChangedEventArgs(propertyName));

        public string GetString(string key, string? language = null)
        {
            language = NormalizeLanguageCode(language ?? CurrentLanguage);

            if (Translations.TryGetValue(language, out var langDict) &&
                langDict.TryGetValue(key, out var langValue))
            {
                return langValue;
            }

            if (Translations.TryGetValue("en", out var enDict) &&
                enDict.TryGetValue(key, out var enValue))
            {
                return enValue;
            }

            if (Translations.TryGetValue("vi", out var viDict) &&
                viDict.TryGetValue(key, out var viValue))
            {
                return viValue;
            }

            return key;
        }

        public List<string> SupportedLanguages => new() { "vi", "en", "zh", "ja", "ru", "fr" };

        public string NormalizeLanguageCode(string? language)
        {
            var normalized = (language ?? "vi").Trim().ToLowerInvariant();
            return normalized switch
            {
                "jp" => "ja",
                _ => normalized
            };
        }

        public string GetLanguageDisplayName(string language)
        {
            var normalized = NormalizeLanguageCode(language);
            return normalized switch
            {
                "vi" => "🇻🇳 Tiếng Việt",
                "en" => "🇬🇧 English",
                "zh" => "🇨🇳 中文",
                "ja" => "🇯🇵 日本語",
                "ru" => "🇷🇺 Русский",
                "fr" => "🇫🇷 Français",
                _ => normalized
            };
        }
    }
}